<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.2 INSTALLER - Wednesday 11th of June 2014 09:12:28 AM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => URL . "/extensions/members_hybridauth/lib/hybridauth/",

		"providers" => array ( 
			// openid providers
			"OpenID" => array (
				"enabled" => true
			),

			"AOL"  => array ( 
				"enabled" => true 
			),

			"Yahoo" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"Google" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => Symphony::Configuration()->get('googleid', 'members_hybridauth'), "secret" => Symphony::Configuration()->get('googlesecret', 'members_hybridauth') )
			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => Symphony::Configuration()->get('facebookid', 'members_hybridauth'), "secret" => Symphony::Configuration()->get('facebooksecret', 'members_hybridauth') )
			),

			"Twitter" => array ( 
				"enabled" => false,
				"keys"    => array ( "key" => "nVghNwviBfwo2ucDzqUtu9Ky0", "secret" => "hIVATNkafjPlpROIGsLjxr2Bva6XQ7Pkxc0Qr5Akl0jYpyfjjD" ) 
			),

			// windows live
			"Live" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),

			"MySpace" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"LinkedIn" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"Foursquare" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
